# @package _global_

# MSMT17 dataset configuration
data:
  dataset: msmt17
  root_dir: ./data/msmt17
  batch_size: 64
  num_instances: 4
  num_workers: 8
  sampler: softmax_triplet

  img_size_train: [384, 128]
  img_size_test: [384, 128]
